///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FuelTypeModelData {
/*
{
  "id": 1,
  "type": "Octane 87",
  "price": "15.99",
  "created_at": "2023-08-18 05:17:08",
  "updated_at": "2023-08-18 05:17:08",
  "deleted_at": ""
} 
*/

  int? id;
  String? type;
  String? price;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  FuelTypeModelData({
    this.id,
    this.type,
    this.price,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  FuelTypeModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    type = json['type']?.toString();
    price = json['price']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['price'] = price;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class FuelTypeModel {
/*
{
  "status": true,
  "message": "Fuel type found successfully.",
  "data": [
    {
      "id": 1,
      "type": "Octane 87",
      "price": "15.99",
      "created_at": "2023-08-18 05:17:08",
      "updated_at": "2023-08-18 05:17:08",
      "deleted_at": ""
    }
  ]
} 
*/

  bool? status;
  String? message;
  List<FuelTypeModelData>? data;

  FuelTypeModel({
    this.status,
    this.message,
    this.data,
  });
  FuelTypeModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <FuelTypeModelData>[];
  v.forEach((v) {
  arr0.add(FuelTypeModelData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}
