///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddVehicleModelData {
/*
{
  "id": 5,
  "name": "My Car",
  "make_id": "1",
  "model_id": "1",
  "color_id": "1",
  "license_plate": "78145ddd",
  "state_id": "1",
  "user_id": 19,
  "updated_at": "2023-09-06 05:56:28",
  "created_at": "2023-09-06 05:56:28"
} 
*/

  int? id;
  String? name;
  String? makeId;
  String? modelId;
  String? colorId;
  String? licensePlate;
  String? stateId;
  int? userId;
  String? updatedAt;
  String? createdAt;

  AddVehicleModelData({
    this.id,
    this.name,
    this.makeId,
    this.modelId,
    this.colorId,
    this.licensePlate,
    this.stateId,
    this.userId,
    this.updatedAt,
    this.createdAt,
  });
  AddVehicleModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    makeId = json['make_id']?.toString();
    modelId = json['model_id']?.toString();
    colorId = json['color_id']?.toString();
    licensePlate = json['license_plate']?.toString();
    stateId = json['state_id']?.toString();
    userId = json['user_id']?.toInt();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['make_id'] = makeId;
    data['model_id'] = modelId;
    data['color_id'] = colorId;
    data['license_plate'] = licensePlate;
    data['state_id'] = stateId;
    data['user_id'] = userId;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    return data;
  }
}

class AddVehicleModel {
/*
{
  "status": true,
  "message": "Vehicle added successfully.",
  "data": {
    "id": 5,
    "name": "My Car",
    "make_id": "1",
    "model_id": "1",
    "color_id": "1",
    "license_plate": "78145ddd",
    "state_id": "1",
    "user_id": 19,
    "updated_at": "2023-09-06 05:56:28",
    "created_at": "2023-09-06 05:56:28"
  }
} 
*/

  bool? status;
  String? message;
  AddVehicleModelData? data;

  AddVehicleModel({
    this.status,
    this.message,
    this.data,
  });
  AddVehicleModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? AddVehicleModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
